-- MySQL Script generated by MySQL Workbench
-- Wed 19 Apr 2017 06:10:25 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------
-- Blog tutorial schemas.
DROP SCHEMA IF EXISTS `Blog` ;

-- -----------------------------------------------------
-- Schema Blog
--
-- Blog tutorial schemas.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog` DEFAULT CHARACTER SET utf8 ;
USE `Blog` ;

-- -----------------------------------------------------
-- Table `Blog`.`blog_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_author` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_author` (
  `id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Blog`.`blog_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_category` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `date_created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Blog`.`blog_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_post` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(144) NOT NULL,
  `article` LONGTEXT NULL DEFAULT NULL,
  `thumbnail` LONGTEXT NULL DEFAULT NULL,
  `date_published` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `featured` TINYINT(1) NOT NULL DEFAULT '0',
  `enabled` TINYINT(1) NOT NULL DEFAULT '0',
  `comments_enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `views` INT(11) NOT NULL DEFAULT '0',
  `blog_author_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blog_post_blog_author1_idx` (`blog_author_id` ASC),
  CONSTRAINT `FK_blog_post_blog_author`
    FOREIGN KEY (`blog_author_id`)
    REFERENCES `Blog`.`blog_author` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Blog`.`blog_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_user` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_user` (
  `id` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `website` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Blog`.`blog_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_comment` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `is_reply_to_id` INT(11) NOT NULL DEFAULT '0',
  `comment` TEXT NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `mark_read` TINYINT(1) NULL DEFAULT '0',
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `FK_blog_comment_blog_post` (`post_id` ASC),
  INDEX `FK_blog_comment_blog_user` (`user_id` ASC),
  CONSTRAINT `FK_blog_comment_blog_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `Blog`.`blog_post` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_blog_comment_blog_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Blog`.`blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Blog`.`blog_post_to_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_post_to_category` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_post_to_category` (
  `category_id` INT(11) NOT NULL,
  `post_id` INT(11) NOT NULL,
  PRIMARY KEY (`category_id`, `post_id`),
  INDEX `fk_posts_to_categories_1` (`category_id` ASC),
  INDEX `fk_posts_to_categories_2` (`post_id` ASC),
  CONSTRAINT `fk_posts_to_categories_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Blog`.`blog_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_to_categories_2`
    FOREIGN KEY (`post_id`)
    REFERENCES `Blog`.`blog_post` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Blog`.`blog_related`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_related` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_related` (
  `blog_post_id` INT(11) NOT NULL,
  `blog_related_post_id` INT(11) NOT NULL,
  PRIMARY KEY (`blog_post_id`, `blog_related_post_id`),
  INDEX `fk_blog_related_1` (`blog_post_id` ASC),
  CONSTRAINT `fk_blog_related_1`
    FOREIGN KEY (`blog_post_id`)
    REFERENCES `Blog`.`blog_post` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Blog`.`blog_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`blog_tag` ;

CREATE TABLE IF NOT EXISTS `Blog`.`blog_tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_1` (`post_id` ASC),
  CONSTRAINT `fk_tags_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `Blog`.`blog_post` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
