#ifndef TRIPLESERVER_H
#define TRIPLESERVER_H

// Qt stuff here...
#include <QtWebSockets/QWebSocketServer>
#include <QSettings>
#include <QStringList>
#include <QMap>
#include <QJsonArray>
#include <QJsonObject>

/**
 * @brief Service Container is a TCP server. It's use to interface
 * c++ class functionality over a network.
 */
class ServiceContainer : public QWebSocketServer
{

    Q_OBJECT
public:
    explicit ServiceContainer(const QString &serverName, SslMode secureMode,
                              QObject *parent = Q_NULLPTR);
    void startServer();
    virtual ~ServiceContainer();

    /**
     * A singleton to the server
     **/
    static ServiceContainer *getInstance();

    /**
     * Set port.
     */
    void setPort(quint16 port);

    /**
     * Get an object with his typeName.
     **/
    QObject* getObjectByTypeName(QString typeName);

Q_SIGNALS:
    void closed();

private Q_SLOTS:
    void onNewConnection();

public Q_SLOTS:
    //////////////////////////////////////////////
    // Service Container api.
    /////////////////////////////////////////////

    /**
     * @brief Ping
     * @return
     */
    QString Ping();

    /**
     * @brief ExecuteJsFunction
     * That function is use to run JS script. It return a list of QObject.
     * @return A list of object generated by the script.
     */
    QVariantList ExecuteJsFunction(QVariantList);


    /**
     * @brief GetServicesClientCode
     * Return the client side source code to inject in the VM to be able to
     * make remote methode call.
     * @return
     */
    QString GetServicesClientCode();


    /**
     * @brief GetActionInfos
     * Return plugin and array of JSON object of the form:
     * [{"IID":"plugin_1",
     *  "actions":[
     *              { "name":"action_1","doc":"@api 1.0... ",
     *                "parameters":[{"name":"p0", "type":"string", "isArray":"false"}, ...],
     *                "results":[{"name":"r0", "type":"string", "isArray":"false"}, ...]
     *              ]}, ...
     *             ]}
     * ]
     * @return
     */
    QJsonArray GetActionInfos();

private:
    // plugins...
    void loadPluginObjects();

    // The port
    quint16 port;

    // Object define by plugin...
    QMap<QString, QObject*> objects;

    // Contain metadata informations.
    QMap<QString, QJsonObject> metaInfos;

    // The instance to the server itself...
    static ServiceContainer* instance;
};

#endif // TRIPLESERVER_H
