///////////////////////////////////////////////////////////////////////////////////////////////////
// Those classes are exemple how to connect backend whit interface.
// 
//////////////////////////////////////////////////////////////////////////////////////////////////

// When a user is connected 
var Session = function () {
    // The name of the releation within it parent object, in that case
    // the account object.
    ParentLnk = "M_sessions"
    ParentUuid = "CargoEntities.Account%c1f0d890-34bd-3639-ab23-abfca6de734b"

    // The class type name
    TYPENAME = "CargoEntities.Session"
    UUID = "CargoEntities.Session%34aa9d97-3b4f-3022-9c2d-d9095d71010b"

    // The account uuid...
    M_accountPtr = "CargoEntities.Account%c1f0d890-34bd-3639-ab23-abfca6de734b"
    
    // The computer reference where the user is log in.
    M_computerRef = ""
    // The session end time
    M_endTime = 0
    // The connection id on the server, that value are generated by the server at connection time.
    M_id = "0fe304be-a7cb-46ad-916d-8158805d6e4e"
    // The session state, 1:online, 2:Away, 3:offline
    M_sessionState = 1
    // The session start time
    M_startTime = Math.round(new Date().getTime() / 1000)
    // The session time since the status change.
    M_statusTime = M_startTime // same as start time to begin...
}

var SessionManager = function () {
    // Account is information store on the server side.
    this.account = { "name": "admin", "email": "admin@admin.com", "pwd": "adminadmin", "user": { "firstName": "Jonh", "lastName": "doe" } }
    return this;
}

SessionManager.prototype.login = function (email, pwd, successCallback, errorCallback) {
    if (this.account.email != email) {
        errorCallback("unknow email address " + email)
        return
    }

    if (this.account.pwd != pwd) {
        errorCallback("wrong password for " + email)
        return
    }

    // Return specific user information here.
    successCallback(new Session())
}

// Set the session manager mockup object.
server.sessionManager = new SessionManager()