// +build BPMS

package BPMS

type FlowNodeType int
const(
	FlowNodeType_AbstractTask FlowNodeType = 1+iota
	FlowNodeType_ServiceTask
	FlowNodeType_UserTask
	FlowNodeType_ManualTask
	FlowNodeType_BusinessRuleTask
	FlowNodeType_ScriptTask
	FlowNodeType_EmbeddedSubprocess
	FlowNodeType_EventSubprocess
	FlowNodeType_AdHocSubprocess
	FlowNodeType_Transaction
	FlowNodeType_CallActivity
	FlowNodeType_ParallelGateway
	FlowNodeType_ExclusiveGateway
	FlowNodeType_InclusiveGateway
	FlowNodeType_EventBasedGateway
	FlowNodeType_ComplexGateway
	FlowNodeType_StartEvent
	FlowNodeType_IntermediateCatchEvent
	FlowNodeType_BoundaryEvent
	FlowNodeType_EndEvent
	FlowNodeType_IntermediateThrowEvent
)
