// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"code.myceliUs.com/CargoWebServer/Cargo/QueryParser/token"
)

const (
	NoState    = -1
	NumStates  = 90
	NumSymbols = 135
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '-'
1: '-'
2: '.'
3: '"'
4: ' '
5: '"'
6: '/'
7: '\'
8: '|'
9: ' '
10: '/'
11: 'n'
12: 'u'
13: 'l'
14: 'l'
15: 't'
16: 'r'
17: 'u'
18: 'e'
19: 'f'
20: 'a'
21: 'l'
22: 's'
23: 'e'
24: '_'
25: '_'
26: '!'
27: '='
28: '='
29: '='
30: '~'
31: '='
32: '>'
33: '<'
34: '>'
35: '='
36: '<'
37: '='
38: '^'
39: '='
40: '$'
41: '='
42: '&'
43: '&'
44: '|'
45: '|'
46: '('
47: ')'
48: '.'
49: 'e'
50: 'E'
51: '+'
52: '-'
53: '\'
54: '\'
55: '\'
56: '\'
57: 'u'
58: '\'
59: 'b'
60: 't'
61: 'n'
62: 'f'
63: 'r'
64: '"'
65: '''
66: '\'
67: '\'
68: '{'
69: '}'
70: '('
71: ')'
72: '['
73: ']'
74: '/'
75: '\'
76: '|'
77: \u00c9
78: \u00e9
79: \u00e8
80: \u00c8
81: \u00ea
82: \u00ca
83: \u00e0
84: \u00c0
85: \u00c7
86: \u00eb
87: \u00cb
88: \u00d4
89: \u00f4
90: '?'
91: '!'
92: '.'
93: ','
94: ':'
95: ';'
96: '`'
97: '_'
98: '~'
99: '@'
100: '#'
101: '`'
102: '^'
103: '%'
104: '-'
105: '+'
106: '*'
107: '$'
108: '='
109: '<'
110: '>'
111: '!'
112: '\t'
113: '\n'
114: '\r'
115: ' '
116: '1'-'9'
117: 'a'-'z'
118: 'A'-'Z'
119: 'a'-'z'
120: 'A'-'Z'
121: '0'-'9'
122: '0'-'9'
123: '0'-'9'
124: 'a'-'f'
125: 'A'-'F'
126: '0'-'3'
127: '0'-'7'
128: '0'-'7'
129: '0'-'7'
130: '0'-'7'
131: '0'-'7'
132: 'a'-'z'
133: 'A'-'Z'
134: .
*/
