
// generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(2),		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			shift(4),		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			shift(5),		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(7),		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			shift(4),		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			shift(9),		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			shift(10),		/* . */
			
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			shift(11),		/* . */
			
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(2),		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			shift(4),		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			shift(13),		/* ) */
			shift(14),		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(7),		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			shift(4),		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			shift(16),		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			shift(10),		/* . */
			
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			shift(18),		/* int64 */
			shift(19),		/* float64 */
			shift(20),		/* string */
			shift(21),		/* boolean */
			shift(22),		/* regex */
			shift(23),		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			shift(24),		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			shift(25),		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Query */
			nil,		/* ( */
			nil,		/* ) */
			shift(5),		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Query */
			nil,		/* ( */
			nil,		/* ) */
			reduce(1),		/* operator, reduce: Query */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(7),		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			shift(4),		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			shift(27),		/* ) */
			shift(14),		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			nil,		/* comparator */
			shift(29),		/* int64 */
			shift(30),		/* float64 */
			shift(31),		/* string */
			shift(32),		/* boolean */
			shift(33),		/* regex */
			shift(34),		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Query */
			nil,		/* ( */
			nil,		/* ) */
			reduce(3),		/* operator, reduce: Query */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Value */
			nil,		/* ( */
			nil,		/* ) */
			reduce(4),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: Value */
			nil,		/* ( */
			nil,		/* ) */
			reduce(5),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: Value */
			nil,		/* ( */
			nil,		/* ) */
			reduce(6),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(7),		/* $, reduce: Value */
			nil,		/* ( */
			nil,		/* ) */
			reduce(7),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(8),		/* $, reduce: Value */
			nil,		/* ( */
			nil,		/* ) */
			reduce(8),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: Value */
			nil,		/* ( */
			nil,		/* ) */
			reduce(9),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			reduce(11),		/* comparator, reduce: Object */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			reduce(11),		/* ., reduce: Object */
			
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			nil,		/* ) */
			nil,		/* operator */
			reduce(10),		/* comparator, reduce: Object */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			reduce(10),		/* ., reduce: Object */
			
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(2),		/* ), reduce: Query */
			shift(14),		/* operator */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(1),		/* ), reduce: Query */
			reduce(1),		/* operator, reduce: Query */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(3),		/* ), reduce: Query */
			reduce(3),		/* operator, reduce: Query */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(4),		/* ), reduce: Value */
			reduce(4),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(5),		/* ), reduce: Value */
			reduce(5),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(6),		/* ), reduce: Value */
			reduce(6),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(7),		/* ), reduce: Value */
			reduce(7),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(8),		/* ), reduce: Value */
			reduce(8),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* ( */
			reduce(9),		/* ), reduce: Value */
			reduce(9),		/* operator, reduce: Value */
			nil,		/* comparator */
			nil,		/* int64 */
			nil,		/* float64 */
			nil,		/* string */
			nil,		/* boolean */
			nil,		/* regex */
			nil,		/* null */
			nil,		/* id */
			nil,		/* . */
			
		},
	},
	
}

