
// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1, // Query
		-1, // Value
		3, // Object
		
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S2
		-1, // S'
		6, // Query
		-1, // Value
		8, // Object
		
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S5
		-1, // S'
		12, // Query
		-1, // Value
		3, // Object
		
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S7
		-1, // S'
		15, // Query
		-1, // Value
		8, // Object
		
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Query
		17, // Value
		-1, // Object
		
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S14
		-1, // S'
		25, // Query
		-1, // Value
		8, // Object
		
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Query
		27, // Value
		-1, // Object
		
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Query
		-1, // Value
		-1, // Object
		
	},
	
}
