#ifndef SAYHELLOPLUGIN_GLOBAL_H
#define SAYHELLOPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAYHELLOPLUGIN_LIBRARY)
#  define SAYHELLOPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAYHELLOPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAYHELLOPLUGIN_GLOBAL_H
