/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: GoJerryScript.i

package GoJerryScript

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef void* swig_type_9;
typedef void* swig_type_10;
typedef void* swig_type_11;
typedef void* swig_type_12;
typedef void* swig_type_13;
typedef void* swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
extern void _wrap_Swig_free_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern swig_intgo _wrap_JERRY_INIT_EMPTY_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_INIT_SHOW_OPCODES_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_INIT_SHOW_REGEXP_OPCODES_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_INIT_MEM_STATS_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_INIT_MEM_STATS_SEPARATE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_INIT_DEBUGGER_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_NONE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_COMMON_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_EVAL_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_RANGE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_REFERENCE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_SYNTAX_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_TYPE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_ERROR_URI_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_CPOINTER_32_BIT_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_ERROR_MESSAGES_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_JS_PARSER_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_MEM_STATS_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_PARSER_DUMP_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_REGEXP_DUMP_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_SNAPSHOT_SAVE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_SNAPSHOT_EXEC_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_DEBUGGER_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_VM_EXEC_STOP_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_JSON_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_PROMISE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_TYPEDARRAY_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_DATE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_REGEXP_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE_LINE_INFO_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_FEATURE__COUNT_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_PARSE_NO_OPTS_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_PARSE_STRICT_MODE_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_jerry_property_descriptor_t_is_value_defined_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_value_defined_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_get_defined_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_get_defined_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_set_defined_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_set_defined_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_writable_defined_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_writable_defined_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_writable_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_writable_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_enumerable_defined_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_enumerable_defined_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_enumerable_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_enumerable_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_configurable_defined_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_configurable_defined_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_is_configurable_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_jerry_property_descriptor_t_is_configurable_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_value_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_property_descriptor_t_value_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_getter_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_property_descriptor_t_getter_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_property_descriptor_t_setter_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_property_descriptor_t_setter_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_new_jerry_property_descriptor_t_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_delete_jerry_property_descriptor_t_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_heap_stats_t_version_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_jerry_heap_stats_t_version_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_heap_stats_t_size_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_jerry_heap_stats_t_size_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_heap_stats_t_allocated_bytes_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_jerry_heap_stats_t_allocated_bytes_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_heap_stats_t_peak_allocated_bytes_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_7 arg2);
extern swig_type_8 _wrap_jerry_heap_stats_t_peak_allocated_bytes_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_heap_stats_t_reserved_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_jerry_heap_stats_t_reserved_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_new_jerry_heap_stats_t_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_delete_jerry_heap_stats_t_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_context_data_manager_t_init_cb_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_9 arg2);
extern swig_type_10 _wrap_jerry_context_data_manager_t_init_cb_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_context_data_manager_t_deinit_cb_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_11 arg2);
extern swig_type_12 _wrap_jerry_context_data_manager_t_deinit_cb_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_context_data_manager_t_finalize_cb_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_13 arg2);
extern swig_type_14 _wrap_jerry_context_data_manager_t_finalize_cb_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_context_data_manager_t_bytes_needed_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_15 arg2);
extern swig_type_16 _wrap_jerry_context_data_manager_t_bytes_needed_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_new_jerry_context_data_manager_t_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_delete_jerry_context_data_manager_t_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_object_native_info_t_free_cb_set_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_jerry_object_native_info_t_free_cb_get_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_new_jerry_object_native_info_t_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_delete_jerry_object_native_info_t_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_init_GoJerryScript_8ba631a7412d8d81(swig_intgo arg1);
extern void _wrap_jerry_cleanup_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_jerry_register_magic_strings_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_jerry_gc_GoJerryScript_8ba631a7412d8d81(void);
extern uintptr_t _wrap_jerry_get_context_data_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_get_memory_stats_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_run_simple_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_17 arg2, swig_intgo arg3);
extern uintptr_t _wrap_jerry_parse_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_18 arg2, uintptr_t arg3, swig_type_19 arg4, uintptr_t arg5);
extern uintptr_t _wrap_jerry_parse_function_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_20 arg2, uintptr_t arg3, swig_type_21 arg4, uintptr_t arg5, swig_type_22 arg6, uintptr_t arg7);
extern uintptr_t _wrap_jerry_run_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_eval_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_type_23 arg2, _Bool arg3);
extern uintptr_t _wrap_jerry_run_all_enqueued_jobs_GoJerryScript_8ba631a7412d8d81(void);
extern uintptr_t _wrap_jerry_get_global_object_GoJerryScript_8ba631a7412d8d81(void);
extern _Bool _wrap_jerry_value_is_abort_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_array_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_boolean_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_constructor_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_error_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_function_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_number_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_null_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_object_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_promise_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_string_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_undefined_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern swig_intgo _wrap_JERRY_TYPE_NONE_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPE_UNDEFINED_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPE_NULL_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPE_BOOLEAN_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPE_NUMBER_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPE_STRING_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPE_OBJECT_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPE_FUNCTION_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_jerry_value_get_type_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_is_feature_enabled_GoJerryScript_8ba631a7412d8d81(swig_intgo arg1);
extern uintptr_t _wrap_jerry_get_value_from_error_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, _Bool arg2);
extern void _wrap_jerry_value_set_error_flag_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_value_set_abort_flag_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern swig_intgo _wrap_jerry_get_error_type_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_get_boolean_value_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern double _wrap_jerry_get_number_value_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_string_size_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_utf8_string_size_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_string_length_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_utf8_string_length_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_string_to_char_buffer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_string_to_utf8_char_buffer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_substring_to_char_buffer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5);
extern uintptr_t _wrap_jerry_substring_to_utf8_char_buffer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5);
extern uintptr_t _wrap_jerry_get_array_length_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_to_boolean_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_value_to_number_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_value_to_object_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_value_to_primitive_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_value_to_string_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_acquire_value_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern void _wrap_jerry_release_value_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_create_array_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_create_boolean_GoJerryScript_8ba631a7412d8d81(_Bool arg1);
extern uintptr_t _wrap_jerry_create_error_GoJerryScript_8ba631a7412d8d81(swig_intgo arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_create_error_sz_GoJerryScript_8ba631a7412d8d81(swig_intgo arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_create_external_function_GoJerryScript_8ba631a7412d8d81(swig_voidp arg1);
extern uintptr_t _wrap_jerry_create_number_GoJerryScript_8ba631a7412d8d81(double arg1);
extern uintptr_t _wrap_jerry_create_number_infinity_GoJerryScript_8ba631a7412d8d81(_Bool arg1);
extern uintptr_t _wrap_jerry_create_number_nan_GoJerryScript_8ba631a7412d8d81(void);
extern uintptr_t _wrap_jerry_create_null_GoJerryScript_8ba631a7412d8d81(void);
extern uintptr_t _wrap_jerry_create_object_GoJerryScript_8ba631a7412d8d81(void);
extern uintptr_t _wrap_jerry_create_promise_GoJerryScript_8ba631a7412d8d81(void);
extern uintptr_t _wrap_jerry_create_string_from_utf8_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_create_string_sz_from_utf8_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_create_string_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_create_string_sz_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_create_undefined_GoJerryScript_8ba631a7412d8d81(void);
extern uintptr_t _wrap_jerry_has_property_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_has_own_property_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_jerry_delete_property_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_jerry_delete_property_by_index_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_get_property_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_get_property_by_index_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_set_property_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_set_property_by_index_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_jerry_init_property_descriptor_fields_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_define_own_property_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern _Bool _wrap_jerry_get_own_property_descriptor_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_jerry_free_property_descriptor_fields_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_call_function_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern uintptr_t _wrap_jerry_construct_object_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_get_object_keys_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_prototype_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_set_prototype_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_jerry_get_object_native_handle_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_jerry_set_object_native_handle_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern _Bool _wrap_jerry_get_object_native_pointer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern _Bool _wrap_jerry_objects_foreach_GoJerryScript_8ba631a7412d8d81(swig_voidp arg1, uintptr_t arg2);
extern _Bool _wrap_jerry_objects_foreach_by_native_info_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern void _wrap_jerry_set_object_native_pointer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern _Bool _wrap_jerry_foreach_object_property_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_resolve_or_reject_promise_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, _Bool arg3);
extern _Bool _wrap_jerry_is_valid_utf8_string_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_jerry_is_valid_cesu8_string_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_create_instance_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern void _wrap_jerry_set_vm_exec_stop_callback_GoJerryScript_8ba631a7412d8d81(swig_voidp arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_get_backtrace_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_value_is_arraybuffer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_create_arraybuffer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_create_arraybuffer_external_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern uintptr_t _wrap_jerry_arraybuffer_write_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern uintptr_t _wrap_jerry_arraybuffer_read_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern uintptr_t _wrap_jerry_get_arraybuffer_byte_length_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_arraybuffer_pointer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_INVALID_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_UINT8_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_UINT8CLAMPED_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_INT8_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_UINT16_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_INT16_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_UINT32_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_INT32_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_FLOAT32_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_TYPEDARRAY_FLOAT64_GoJerryScript_8ba631a7412d8d81(void);
extern _Bool _wrap_jerry_value_is_typedarray_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_create_typedarray_GoJerryScript_8ba631a7412d8d81(swig_intgo arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_create_typedarray_for_arraybuffer_sz_GoJerryScript_8ba631a7412d8d81(swig_intgo arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern uintptr_t _wrap_jerry_create_typedarray_for_arraybuffer_GoJerryScript_8ba631a7412d8d81(swig_intgo arg1, uintptr_t arg2);
extern swig_intgo _wrap_jerry_get_typedarray_type_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_typedarray_length_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern uintptr_t _wrap_jerry_get_typedarray_buffer_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerry_json_parse_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_jerry_json_stringfy_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern swig_intgo _wrap_JERRY_DEBUGGER_SOURCE_RECEIVE_FAILED_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_DEBUGGER_SOURCE_RECEIVED_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_DEBUGGER_SOURCE_END_GoJerryScript_8ba631a7412d8d81(void);
extern swig_intgo _wrap_JERRY_DEBUGGER_CONTEXT_RESET_RECEIVED_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_jerry_debugger_init_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1);
extern _Bool _wrap_jerry_debugger_is_connected_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_jerry_debugger_stop_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_jerry_debugger_continue_GoJerryScript_8ba631a7412d8d81(void);
extern void _wrap_jerry_debugger_stop_at_breakpoint_GoJerryScript_8ba631a7412d8d81(_Bool arg1);
extern swig_intgo _wrap_jerry_debugger_wait_for_client_source_GoJerryScript_8ba631a7412d8d81(swig_voidp arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_jerry_debugger_send_output_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_jerryx_handler_register_global_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, swig_voidp arg2);
extern uintptr_t _wrap_jerryx_handler_assert_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern uintptr_t _wrap_jerryx_handler_gc_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern uintptr_t _wrap_jerryx_handler_print_GoJerryScript_8ba631a7412d8d81(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4);
extern void _wrap_jerryx_port_handler_print_char_GoJerryScript_8ba631a7412d8d81(char arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

const JERRY_API_MAJOR_VERSION int = 1
const JERRY_API_MINOR_VERSION int = 0
type Jerry_init_flag_t int
func _swig_getJERRY_INIT_EMPTY() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_INIT_EMPTY_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_INIT_EMPTY int = _swig_getJERRY_INIT_EMPTY()
func _swig_getJERRY_INIT_SHOW_OPCODES() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_INIT_SHOW_OPCODES_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_INIT_SHOW_OPCODES int = _swig_getJERRY_INIT_SHOW_OPCODES()
func _swig_getJERRY_INIT_SHOW_REGEXP_OPCODES() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_INIT_SHOW_REGEXP_OPCODES_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_INIT_SHOW_REGEXP_OPCODES int = _swig_getJERRY_INIT_SHOW_REGEXP_OPCODES()
func _swig_getJERRY_INIT_MEM_STATS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_INIT_MEM_STATS_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_INIT_MEM_STATS int = _swig_getJERRY_INIT_MEM_STATS()
func _swig_getJERRY_INIT_MEM_STATS_SEPARATE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_INIT_MEM_STATS_SEPARATE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_INIT_MEM_STATS_SEPARATE int = _swig_getJERRY_INIT_MEM_STATS_SEPARATE()
func _swig_getJERRY_INIT_DEBUGGER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_INIT_DEBUGGER_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_INIT_DEBUGGER int = _swig_getJERRY_INIT_DEBUGGER()
type Jerry_error_t int
func _swig_getJERRY_ERROR_NONE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_NONE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_NONE int = _swig_getJERRY_ERROR_NONE()
func _swig_getJERRY_ERROR_COMMON() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_COMMON_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_COMMON int = _swig_getJERRY_ERROR_COMMON()
func _swig_getJERRY_ERROR_EVAL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_EVAL_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_EVAL int = _swig_getJERRY_ERROR_EVAL()
func _swig_getJERRY_ERROR_RANGE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_RANGE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_RANGE int = _swig_getJERRY_ERROR_RANGE()
func _swig_getJERRY_ERROR_REFERENCE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_REFERENCE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_REFERENCE int = _swig_getJERRY_ERROR_REFERENCE()
func _swig_getJERRY_ERROR_SYNTAX() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_SYNTAX_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_SYNTAX int = _swig_getJERRY_ERROR_SYNTAX()
func _swig_getJERRY_ERROR_TYPE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_TYPE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_TYPE int = _swig_getJERRY_ERROR_TYPE()
func _swig_getJERRY_ERROR_URI() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_ERROR_URI_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_ERROR_URI int = _swig_getJERRY_ERROR_URI()
type Jerry_feature_t int
func _swig_getJERRY_FEATURE_CPOINTER_32_BIT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_CPOINTER_32_BIT_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_CPOINTER_32_BIT int = _swig_getJERRY_FEATURE_CPOINTER_32_BIT()
func _swig_getJERRY_FEATURE_ERROR_MESSAGES() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_ERROR_MESSAGES_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_ERROR_MESSAGES int = _swig_getJERRY_FEATURE_ERROR_MESSAGES()
func _swig_getJERRY_FEATURE_JS_PARSER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_JS_PARSER_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_JS_PARSER int = _swig_getJERRY_FEATURE_JS_PARSER()
func _swig_getJERRY_FEATURE_MEM_STATS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_MEM_STATS_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_MEM_STATS int = _swig_getJERRY_FEATURE_MEM_STATS()
func _swig_getJERRY_FEATURE_PARSER_DUMP() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_PARSER_DUMP_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_PARSER_DUMP int = _swig_getJERRY_FEATURE_PARSER_DUMP()
func _swig_getJERRY_FEATURE_REGEXP_DUMP() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_REGEXP_DUMP_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_REGEXP_DUMP int = _swig_getJERRY_FEATURE_REGEXP_DUMP()
func _swig_getJERRY_FEATURE_SNAPSHOT_SAVE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_SNAPSHOT_SAVE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_SNAPSHOT_SAVE int = _swig_getJERRY_FEATURE_SNAPSHOT_SAVE()
func _swig_getJERRY_FEATURE_SNAPSHOT_EXEC() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_SNAPSHOT_EXEC_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_SNAPSHOT_EXEC int = _swig_getJERRY_FEATURE_SNAPSHOT_EXEC()
func _swig_getJERRY_FEATURE_DEBUGGER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_DEBUGGER_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_DEBUGGER int = _swig_getJERRY_FEATURE_DEBUGGER()
func _swig_getJERRY_FEATURE_VM_EXEC_STOP() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_VM_EXEC_STOP_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_VM_EXEC_STOP int = _swig_getJERRY_FEATURE_VM_EXEC_STOP()
func _swig_getJERRY_FEATURE_JSON() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_JSON_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_JSON int = _swig_getJERRY_FEATURE_JSON()
func _swig_getJERRY_FEATURE_PROMISE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_PROMISE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_PROMISE int = _swig_getJERRY_FEATURE_PROMISE()
func _swig_getJERRY_FEATURE_TYPEDARRAY() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_TYPEDARRAY_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_TYPEDARRAY int = _swig_getJERRY_FEATURE_TYPEDARRAY()
func _swig_getJERRY_FEATURE_DATE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_DATE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_DATE int = _swig_getJERRY_FEATURE_DATE()
func _swig_getJERRY_FEATURE_REGEXP() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_REGEXP_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_REGEXP int = _swig_getJERRY_FEATURE_REGEXP()
func _swig_getJERRY_FEATURE_LINE_INFO() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE_LINE_INFO_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE_LINE_INFO int = _swig_getJERRY_FEATURE_LINE_INFO()
func _swig_getJERRY_FEATURE__COUNT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_FEATURE__COUNT_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_FEATURE__COUNT int = _swig_getJERRY_FEATURE__COUNT()
type Jerry_parse_opts_t int
func _swig_getJERRY_PARSE_NO_OPTS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_PARSE_NO_OPTS_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_PARSE_NO_OPTS int = _swig_getJERRY_PARSE_NO_OPTS()
func _swig_getJERRY_PARSE_STRICT_MODE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_PARSE_STRICT_MODE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_PARSE_STRICT_MODE int = _swig_getJERRY_PARSE_STRICT_MODE()
type SwigcptrJerry_property_descriptor_t uintptr

func (p SwigcptrJerry_property_descriptor_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJerry_property_descriptor_t) SwigIsJerry_property_descriptor_t() {
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_value_defined(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_value_defined_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_value_defined() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_value_defined_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_get_defined(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_get_defined_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_get_defined() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_get_defined_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_set_defined(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_set_defined_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_set_defined() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_set_defined_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_writable_defined(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_writable_defined_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_writable_defined() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_writable_defined_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_writable(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_writable_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_writable() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_writable_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_enumerable_defined(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_enumerable_defined_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_enumerable_defined() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_enumerable_defined_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_enumerable(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_enumerable_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_enumerable() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_enumerable_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_configurable_defined(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_configurable_defined_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_configurable_defined() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_configurable_defined_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetIs_configurable(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_property_descriptor_t_is_configurable_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetIs_configurable() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_property_descriptor_t_is_configurable_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetValue(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_jerry_property_descriptor_t_value_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetValue() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_property_descriptor_t_value_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetGetter(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_jerry_property_descriptor_t_getter_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetGetter() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_property_descriptor_t_getter_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrJerry_property_descriptor_t) SetSetter(arg2 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_jerry_property_descriptor_t_setter_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrJerry_property_descriptor_t) GetSetter() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_property_descriptor_t_setter_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewJerry_property_descriptor_t() (_swig_ret Jerry_property_descriptor_t) {
	var swig_r Jerry_property_descriptor_t
	swig_r = (Jerry_property_descriptor_t)(SwigcptrJerry_property_descriptor_t(C._wrap_new_jerry_property_descriptor_t_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func DeleteJerry_property_descriptor_t(arg1 Jerry_property_descriptor_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_jerry_property_descriptor_t_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

type Jerry_property_descriptor_t interface {
	Swigcptr() uintptr
	SwigIsJerry_property_descriptor_t()
	SetIs_value_defined(arg2 bool)
	GetIs_value_defined() (_swig_ret bool)
	SetIs_get_defined(arg2 bool)
	GetIs_get_defined() (_swig_ret bool)
	SetIs_set_defined(arg2 bool)
	GetIs_set_defined() (_swig_ret bool)
	SetIs_writable_defined(arg2 bool)
	GetIs_writable_defined() (_swig_ret bool)
	SetIs_writable(arg2 bool)
	GetIs_writable() (_swig_ret bool)
	SetIs_enumerable_defined(arg2 bool)
	GetIs_enumerable_defined() (_swig_ret bool)
	SetIs_enumerable(arg2 bool)
	GetIs_enumerable() (_swig_ret bool)
	SetIs_configurable_defined(arg2 bool)
	GetIs_configurable_defined() (_swig_ret bool)
	SetIs_configurable(arg2 bool)
	GetIs_configurable() (_swig_ret bool)
	SetValue(arg2 Uint32_t)
	GetValue() (_swig_ret Uint32_t)
	SetGetter(arg2 Uint32_t)
	GetGetter() (_swig_ret Uint32_t)
	SetSetter(arg2 Uint32_t)
	GetSetter() (_swig_ret Uint32_t)
}

type SwigcptrJerry_heap_stats_t uintptr

func (p SwigcptrJerry_heap_stats_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJerry_heap_stats_t) SwigIsJerry_heap_stats_t() {
}

func (arg1 SwigcptrJerry_heap_stats_t) SetVersion(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_heap_stats_t_version_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1))
}

func (arg1 SwigcptrJerry_heap_stats_t) GetVersion() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_jerry_heap_stats_t_version_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_heap_stats_t) SetSize(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_heap_stats_t_size_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1))
}

func (arg1 SwigcptrJerry_heap_stats_t) GetSize() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_jerry_heap_stats_t_size_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_heap_stats_t) SetAllocated_bytes(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_heap_stats_t_allocated_bytes_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_5(_swig_i_1))
}

func (arg1 SwigcptrJerry_heap_stats_t) GetAllocated_bytes() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_jerry_heap_stats_t_allocated_bytes_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_heap_stats_t) SetPeak_allocated_bytes(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_heap_stats_t_peak_allocated_bytes_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_7(_swig_i_1))
}

func (arg1 SwigcptrJerry_heap_stats_t) GetPeak_allocated_bytes() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_jerry_heap_stats_t_peak_allocated_bytes_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_heap_stats_t) SetReserved(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_heap_stats_t_reserved_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrJerry_heap_stats_t) GetReserved() (_swig_ret *int64) {
	var swig_r *int64
	_swig_i_0 := arg1
	swig_r = (*int64)(C._wrap_jerry_heap_stats_t_reserved_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJerry_heap_stats_t() (_swig_ret Jerry_heap_stats_t) {
	var swig_r Jerry_heap_stats_t
	swig_r = (Jerry_heap_stats_t)(SwigcptrJerry_heap_stats_t(C._wrap_new_jerry_heap_stats_t_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func DeleteJerry_heap_stats_t(arg1 Jerry_heap_stats_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_jerry_heap_stats_t_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

type Jerry_heap_stats_t interface {
	Swigcptr() uintptr
	SwigIsJerry_heap_stats_t()
	SetVersion(arg2 int64)
	GetVersion() (_swig_ret int64)
	SetSize(arg2 int64)
	GetSize() (_swig_ret int64)
	SetAllocated_bytes(arg2 int64)
	GetAllocated_bytes() (_swig_ret int64)
	SetPeak_allocated_bytes(arg2 int64)
	GetPeak_allocated_bytes() (_swig_ret int64)
	SetReserved(arg2 *int64)
	GetReserved() (_swig_ret *int64)
}

type SwigcptrJerry_context_data_manager_t uintptr

func (p SwigcptrJerry_context_data_manager_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJerry_context_data_manager_t) SwigIsJerry_context_data_manager_t() {
}

func (arg1 SwigcptrJerry_context_data_manager_t) SetInit_cb(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_context_data_manager_t_init_cb_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_9(_swig_i_1))
}

func (arg1 SwigcptrJerry_context_data_manager_t) GetInit_cb() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_jerry_context_data_manager_t_init_cb_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_context_data_manager_t) SetDeinit_cb(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_context_data_manager_t_deinit_cb_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_11(_swig_i_1))
}

func (arg1 SwigcptrJerry_context_data_manager_t) GetDeinit_cb() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_jerry_context_data_manager_t_deinit_cb_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_context_data_manager_t) SetFinalize_cb(arg2 _swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_context_data_manager_t_finalize_cb_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_13(_swig_i_1))
}

func (arg1 SwigcptrJerry_context_data_manager_t) GetFinalize_cb() (_swig_ret _swig_fnptr) {
	var swig_r _swig_fnptr
	_swig_i_0 := arg1
	swig_r = (_swig_fnptr)(C._wrap_jerry_context_data_manager_t_finalize_cb_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrJerry_context_data_manager_t) SetBytes_needed(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_context_data_manager_t_bytes_needed_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_15(_swig_i_1))
}

func (arg1 SwigcptrJerry_context_data_manager_t) GetBytes_needed() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_jerry_context_data_manager_t_bytes_needed_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJerry_context_data_manager_t() (_swig_ret Jerry_context_data_manager_t) {
	var swig_r Jerry_context_data_manager_t
	swig_r = (Jerry_context_data_manager_t)(SwigcptrJerry_context_data_manager_t(C._wrap_new_jerry_context_data_manager_t_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func DeleteJerry_context_data_manager_t(arg1 Jerry_context_data_manager_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_jerry_context_data_manager_t_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

type Jerry_context_data_manager_t interface {
	Swigcptr() uintptr
	SwigIsJerry_context_data_manager_t()
	SetInit_cb(arg2 _swig_fnptr)
	GetInit_cb() (_swig_ret _swig_fnptr)
	SetDeinit_cb(arg2 _swig_fnptr)
	GetDeinit_cb() (_swig_ret _swig_fnptr)
	SetFinalize_cb(arg2 _swig_fnptr)
	GetFinalize_cb() (_swig_ret _swig_fnptr)
	SetBytes_needed(arg2 int64)
	GetBytes_needed() (_swig_ret int64)
}

type SwigcptrJerry_object_native_info_t uintptr

func (p SwigcptrJerry_object_native_info_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrJerry_object_native_info_t) SwigIsJerry_object_native_info_t() {
}

func (arg1 SwigcptrJerry_object_native_info_t) SetFree_cb(arg2 *_swig_fnptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_jerry_object_native_info_t_free_cb_set_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrJerry_object_native_info_t) GetFree_cb() (_swig_ret *_swig_fnptr) {
	var swig_r *_swig_fnptr
	_swig_i_0 := arg1
	swig_r = (*_swig_fnptr)(C._wrap_jerry_object_native_info_t_free_cb_get_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewJerry_object_native_info_t() (_swig_ret Jerry_object_native_info_t) {
	var swig_r Jerry_object_native_info_t
	swig_r = (Jerry_object_native_info_t)(SwigcptrJerry_object_native_info_t(C._wrap_new_jerry_object_native_info_t_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func DeleteJerry_object_native_info_t(arg1 Jerry_object_native_info_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_jerry_object_native_info_t_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

type Jerry_object_native_info_t interface {
	Swigcptr() uintptr
	SwigIsJerry_object_native_info_t()
	SetFree_cb(arg2 *_swig_fnptr)
	GetFree_cb() (_swig_ret *_swig_fnptr)
}

func Jerry_init(arg1 Jerry_init_flag_t) {
	_swig_i_0 := arg1
	C._wrap_jerry_init_GoJerryScript_8ba631a7412d8d81(C.swig_intgo(_swig_i_0))
}

func Jerry_cleanup() {
	C._wrap_jerry_cleanup_GoJerryScript_8ba631a7412d8d81()
}

func Jerry_register_magic_strings(arg1 uintptr, arg2 Uint32_t, arg3 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_jerry_register_magic_strings_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Jerry_gc() {
	C._wrap_jerry_gc_GoJerryScript_8ba631a7412d8d81()
}

func Jerry_get_context_data(arg1 Jerry_context_data_manager_t) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uintptr)(C._wrap_jerry_get_context_data_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_get_memory_stats(arg1 Jerry_heap_stats_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_get_memory_stats_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_run_simple(arg1 Uint8_t, arg2 int64, arg3 Jerry_init_flag_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (bool)(C._wrap_jerry_run_simple_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_17(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Jerry_parse(arg1 Uint8_t, arg2 int64, arg3 Uint8_t, arg4 int64, arg5 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_parse_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_19(_swig_i_3), C.uintptr_t(_swig_i_4))))
	return swig_r
}

func Jerry_parse_function(arg1 Uint8_t, arg2 int64, arg3 Uint8_t, arg4 int64, arg5 Uint8_t, arg6 int64, arg7 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	_swig_i_5 := arg6
	_swig_i_6 := arg7.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_parse_function_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_20(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_21(_swig_i_3), C.uintptr_t(_swig_i_4), C.swig_type_22(_swig_i_5), C.uintptr_t(_swig_i_6))))
	return swig_r
}

func Jerry_run(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_run_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_eval(arg1 Uint8_t, arg2 int64, arg3 bool) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_eval_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_type_23(_swig_i_1), C._Bool(_swig_i_2))))
	return swig_r
}

func Jerry_run_all_enqueued_jobs() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_run_all_enqueued_jobs_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func Jerry_get_global_object() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_global_object_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func Jerry_value_is_abort(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_abort_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_array(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_array_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_boolean(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_boolean_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_constructor(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_constructor_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_error(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_error_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_function(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_function_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_number(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_number_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_null(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_null_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_object(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_object_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_promise(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_promise_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_string(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_string_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_is_undefined(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_undefined_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type Jerry_type_t int
func _swig_getJERRY_TYPE_NONE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_NONE_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_NONE int = _swig_getJERRY_TYPE_NONE()
func _swig_getJERRY_TYPE_UNDEFINED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_UNDEFINED_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_UNDEFINED int = _swig_getJERRY_TYPE_UNDEFINED()
func _swig_getJERRY_TYPE_NULL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_NULL_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_NULL int = _swig_getJERRY_TYPE_NULL()
func _swig_getJERRY_TYPE_BOOLEAN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_BOOLEAN_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_BOOLEAN int = _swig_getJERRY_TYPE_BOOLEAN()
func _swig_getJERRY_TYPE_NUMBER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_NUMBER_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_NUMBER int = _swig_getJERRY_TYPE_NUMBER()
func _swig_getJERRY_TYPE_STRING() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_STRING_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_STRING int = _swig_getJERRY_TYPE_STRING()
func _swig_getJERRY_TYPE_OBJECT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_OBJECT_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_OBJECT int = _swig_getJERRY_TYPE_OBJECT()
func _swig_getJERRY_TYPE_FUNCTION() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPE_FUNCTION_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPE_FUNCTION int = _swig_getJERRY_TYPE_FUNCTION()
func Jerry_value_get_type(arg1 Uint32_t) (_swig_ret Jerry_type_t) {
	var swig_r Jerry_type_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Jerry_type_t)(C._wrap_jerry_value_get_type_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_is_feature_enabled(arg1 Jerry_feature_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_jerry_is_feature_enabled_GoJerryScript_8ba631a7412d8d81(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Jerry_get_value_from_error(arg1 Uint32_t, arg2 bool) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_value_from_error_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))))
	return swig_r
}

func Jerry_value_set_error_flag(arg1 Uint32_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_jerry_value_set_error_flag_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

func Jerry_value_set_abort_flag(arg1 Uint32_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_jerry_value_set_abort_flag_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

func Jerry_get_error_type(arg1 Uint32_t) (_swig_ret Jerry_error_t) {
	var swig_r Jerry_error_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Jerry_error_t)(C._wrap_jerry_get_error_type_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_get_boolean_value(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_get_boolean_value_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_get_number_value(arg1 Uint32_t) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (float64)(C._wrap_jerry_get_number_value_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_get_string_size(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_string_size_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_get_utf8_string_size(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_utf8_string_size_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_get_string_length(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_string_length_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_get_utf8_string_length(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_utf8_string_length_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_string_to_char_buffer(arg1 Uint32_t, arg2 Uint8_t, arg3 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_string_to_char_buffer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_string_to_utf8_char_buffer(arg1 Uint32_t, arg2 Uint8_t, arg3 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_string_to_utf8_char_buffer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_substring_to_char_buffer(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t, arg4 Uint8_t, arg5 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_substring_to_char_buffer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.uintptr_t(_swig_i_4))))
	return swig_r
}

func Jerry_substring_to_utf8_char_buffer(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t, arg4 Uint8_t, arg5 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_substring_to_utf8_char_buffer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.uintptr_t(_swig_i_4))))
	return swig_r
}

func Jerry_get_array_length(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_array_length_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_value_to_boolean(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_to_boolean_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_value_to_number(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_value_to_number_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_value_to_object(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_value_to_object_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_value_to_primitive(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_value_to_primitive_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_value_to_string(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_value_to_string_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_acquire_value(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_acquire_value_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_release_value(arg1 Uint32_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_jerry_release_value_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

func Jerry_create_array(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_array_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_create_boolean(arg1 bool) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_boolean_GoJerryScript_8ba631a7412d8d81(C._Bool(_swig_i_0))))
	return swig_r
}

func Jerry_create_error(arg1 Jerry_error_t, arg2 Uint8_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_error_GoJerryScript_8ba631a7412d8d81(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_create_error_sz(arg1 Jerry_error_t, arg2 Uint8_t, arg3 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_error_sz_GoJerryScript_8ba631a7412d8d81(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_create_external_function(arg1 *_swig_fnptr) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_external_function_GoJerryScript_8ba631a7412d8d81(C.swig_voidp(_swig_i_0))))
	return swig_r
}

func Jerry_create_number(arg1 float64) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_number_GoJerryScript_8ba631a7412d8d81(C.double(_swig_i_0))))
	return swig_r
}

func Jerry_create_number_infinity(arg1 bool) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_number_infinity_GoJerryScript_8ba631a7412d8d81(C._Bool(_swig_i_0))))
	return swig_r
}

func Jerry_create_number_nan() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_number_nan_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func Jerry_create_null() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_null_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func Jerry_create_object() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_object_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func Jerry_create_promise() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_promise_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func Jerry_create_string_from_utf8(arg1 Uint8_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_string_from_utf8_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_create_string_sz_from_utf8(arg1 Uint8_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_string_sz_from_utf8_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_create_string(arg1 Uint8_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_string_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_create_string_sz(arg1 Uint8_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_string_sz_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_create_undefined() (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_undefined_GoJerryScript_8ba631a7412d8d81()))
	return swig_r
}

func Jerry_has_property(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_has_property_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_has_own_property(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_has_own_property_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_delete_property(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_delete_property_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Jerry_delete_property_by_index(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_delete_property_by_index_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Jerry_get_property(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_property_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_get_property_by_index(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_property_by_index_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_set_property(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_set_property_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_set_property_by_index(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_set_property_by_index_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_init_property_descriptor_fields(arg1 Jerry_property_descriptor_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_jerry_init_property_descriptor_fields_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

func Jerry_define_own_property(arg1 Uint32_t, arg2 Uint32_t, arg3 Jerry_property_descriptor_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_define_own_property_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_get_own_property_descriptor(arg1 Uint32_t, arg2 Uint32_t, arg3 Jerry_property_descriptor_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_get_own_property_descriptor_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Jerry_free_property_descriptor_fields(arg1 Jerry_property_descriptor_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_jerry_free_property_descriptor_fields_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

func Jerry_call_function(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t, arg4 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_call_function_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func Jerry_construct_object(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_construct_object_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_get_object_keys(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_object_keys_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_get_prototype(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_prototype_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_set_prototype(arg1 Uint32_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_set_prototype_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_get_object_native_handle(arg1 Uint32_t, arg2 Uintptr_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_get_object_native_handle_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Jerry_set_object_native_handle(arg1 Uint32_t, arg2 Uintptr_t, arg3 *_swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_jerry_set_object_native_handle_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func Jerry_get_object_native_pointer(arg1 Uint32_t, arg2 *uintptr, arg3 Jerry_object_native_info_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_get_object_native_pointer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Jerry_objects_foreach(arg1 *_swig_fnptr, arg2 uintptr) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_jerry_objects_foreach_GoJerryScript_8ba631a7412d8d81(C.swig_voidp(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Jerry_objects_foreach_by_native_info(arg1 Jerry_object_native_info_t, arg2 *_swig_fnptr, arg3 uintptr) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (bool)(C._wrap_jerry_objects_foreach_by_native_info_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Jerry_set_object_native_pointer(arg1 Uint32_t, arg2 uintptr, arg3 Jerry_object_native_info_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_jerry_set_object_native_pointer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Jerry_foreach_object_property(arg1 Uint32_t, arg2 *_swig_fnptr, arg3 uintptr) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (bool)(C._wrap_jerry_foreach_object_property_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Jerry_resolve_or_reject_promise(arg1 Uint32_t, arg2 Uint32_t, arg3 bool) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_resolve_or_reject_promise_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C._Bool(_swig_i_2))))
	return swig_r
}

func Jerry_is_valid_utf8_string(arg1 Uint8_t, arg2 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_is_valid_utf8_string_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Jerry_is_valid_cesu8_string(arg1 Uint8_t, arg2 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_is_valid_cesu8_string_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Jerry_create_instance(arg1 Uint32_t, arg2 *_swig_fnptr, arg3 uintptr) (_swig_ret Jerry_instance_t) {
	var swig_r Jerry_instance_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Jerry_instance_t)(SwigcptrJerry_instance_t(C._wrap_jerry_create_instance_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_set_vm_exec_stop_callback(arg1 *_swig_fnptr, arg2 uintptr, arg3 Uint32_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_jerry_set_vm_exec_stop_callback_GoJerryScript_8ba631a7412d8d81(C.swig_voidp(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Jerry_get_backtrace(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_backtrace_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_value_is_arraybuffer(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_arraybuffer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_create_arraybuffer(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_arraybuffer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_create_arraybuffer_external(arg1 Uint32_t, arg2 Uint8_t, arg3 *_swig_fnptr) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_arraybuffer_external_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))))
	return swig_r
}

func Jerry_arraybuffer_write(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint8_t, arg4 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_arraybuffer_write_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func Jerry_arraybuffer_read(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint8_t, arg4 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_arraybuffer_read_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func Jerry_get_arraybuffer_byte_length(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_arraybuffer_byte_length_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_get_arraybuffer_pointer(arg1 Uint32_t) (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_jerry_get_arraybuffer_pointer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

type Jerry_typedarray_type_t int
func _swig_getJERRY_TYPEDARRAY_INVALID() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_INVALID_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_INVALID int = _swig_getJERRY_TYPEDARRAY_INVALID()
func _swig_getJERRY_TYPEDARRAY_UINT8() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_UINT8_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_UINT8 int = _swig_getJERRY_TYPEDARRAY_UINT8()
func _swig_getJERRY_TYPEDARRAY_UINT8CLAMPED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_UINT8CLAMPED_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_UINT8CLAMPED int = _swig_getJERRY_TYPEDARRAY_UINT8CLAMPED()
func _swig_getJERRY_TYPEDARRAY_INT8() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_INT8_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_INT8 int = _swig_getJERRY_TYPEDARRAY_INT8()
func _swig_getJERRY_TYPEDARRAY_UINT16() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_UINT16_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_UINT16 int = _swig_getJERRY_TYPEDARRAY_UINT16()
func _swig_getJERRY_TYPEDARRAY_INT16() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_INT16_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_INT16 int = _swig_getJERRY_TYPEDARRAY_INT16()
func _swig_getJERRY_TYPEDARRAY_UINT32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_UINT32_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_UINT32 int = _swig_getJERRY_TYPEDARRAY_UINT32()
func _swig_getJERRY_TYPEDARRAY_INT32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_INT32_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_INT32 int = _swig_getJERRY_TYPEDARRAY_INT32()
func _swig_getJERRY_TYPEDARRAY_FLOAT32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_FLOAT32_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_FLOAT32 int = _swig_getJERRY_TYPEDARRAY_FLOAT32()
func _swig_getJERRY_TYPEDARRAY_FLOAT64() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_TYPEDARRAY_FLOAT64_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_TYPEDARRAY_FLOAT64 int = _swig_getJERRY_TYPEDARRAY_FLOAT64()
func Jerry_value_is_typedarray(arg1 Uint32_t) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_jerry_value_is_typedarray_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_create_typedarray(arg1 Jerry_typedarray_type_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_typedarray_GoJerryScript_8ba631a7412d8d81(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_create_typedarray_for_arraybuffer_sz(arg1 Jerry_typedarray_type_t, arg2 Uint32_t, arg3 Uint32_t, arg4 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_typedarray_for_arraybuffer_sz_GoJerryScript_8ba631a7412d8d81(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func Jerry_create_typedarray_for_arraybuffer(arg1 Jerry_typedarray_type_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_create_typedarray_for_arraybuffer_GoJerryScript_8ba631a7412d8d81(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_get_typedarray_type(arg1 Uint32_t) (_swig_ret Jerry_typedarray_type_t) {
	var swig_r Jerry_typedarray_type_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Jerry_typedarray_type_t)(C._wrap_jerry_get_typedarray_type_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Jerry_get_typedarray_length(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_typedarray_length_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Jerry_get_typedarray_buffer(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_get_typedarray_buffer_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func Jerry_json_parse(arg1 Uint8_t, arg2 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_json_parse_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Jerry_json_stringfy(arg1 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerry_json_stringfy_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))))
	return swig_r
}

type Jerry_debugger_wait_for_source_status_t int
func _swig_getJERRY_DEBUGGER_SOURCE_RECEIVE_FAILED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_DEBUGGER_SOURCE_RECEIVE_FAILED_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_DEBUGGER_SOURCE_RECEIVE_FAILED int = _swig_getJERRY_DEBUGGER_SOURCE_RECEIVE_FAILED()
func _swig_getJERRY_DEBUGGER_SOURCE_RECEIVED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_DEBUGGER_SOURCE_RECEIVED_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_DEBUGGER_SOURCE_RECEIVED int = _swig_getJERRY_DEBUGGER_SOURCE_RECEIVED()
func _swig_getJERRY_DEBUGGER_SOURCE_END() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_DEBUGGER_SOURCE_END_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_DEBUGGER_SOURCE_END int = _swig_getJERRY_DEBUGGER_SOURCE_END()
func _swig_getJERRY_DEBUGGER_CONTEXT_RESET_RECEIVED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_JERRY_DEBUGGER_CONTEXT_RESET_RECEIVED_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

var JERRY_DEBUGGER_CONTEXT_RESET_RECEIVED int = _swig_getJERRY_DEBUGGER_CONTEXT_RESET_RECEIVED()
func Jerry_debugger_init(arg1 Uint16_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_jerry_debugger_init_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0))
}

func Jerry_debugger_is_connected() (_swig_ret bool) {
	var swig_r bool
	swig_r = (bool)(C._wrap_jerry_debugger_is_connected_GoJerryScript_8ba631a7412d8d81())
	return swig_r
}

func Jerry_debugger_stop() {
	C._wrap_jerry_debugger_stop_GoJerryScript_8ba631a7412d8d81()
}

func Jerry_debugger_continue() {
	C._wrap_jerry_debugger_continue_GoJerryScript_8ba631a7412d8d81()
}

func Jerry_debugger_stop_at_breakpoint(arg1 bool) {
	_swig_i_0 := arg1
	C._wrap_jerry_debugger_stop_at_breakpoint_GoJerryScript_8ba631a7412d8d81(C._Bool(_swig_i_0))
}

func Jerry_debugger_wait_for_client_source(arg1 *_swig_fnptr, arg2 uintptr, arg3 Uint32_t) (_swig_ret Jerry_debugger_wait_for_source_status_t) {
	var swig_r Jerry_debugger_wait_for_source_status_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Jerry_debugger_wait_for_source_status_t)(C._wrap_jerry_debugger_wait_for_client_source_GoJerryScript_8ba631a7412d8d81(C.swig_voidp(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Jerry_debugger_send_output(arg1 Uint8_t, arg2 Uint32_t, arg3 Uint8_t) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_jerry_debugger_send_output_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Jerryx_handler_register_global(arg1 Uint8_t, arg2 *_swig_fnptr) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerryx_handler_register_global_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))))
	return swig_r
}

func Jerryx_handler_assert(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t, arg4 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerryx_handler_assert_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func Jerryx_handler_gc(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t, arg4 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerryx_handler_gc_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func Jerryx_handler_print(arg1 Uint32_t, arg2 Uint32_t, arg3 Uint32_t, arg4 Uint32_t) (_swig_ret Uint32_t) {
	var swig_r Uint32_t
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (Uint32_t)(SwigcptrUint32_t(C._wrap_jerryx_handler_print_GoJerryScript_8ba631a7412d8d81(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3))))
	return swig_r
}

func Jerryx_port_handler_print_char(arg1 byte) {
	_swig_i_0 := arg1
	C._wrap_jerryx_port_handler_print_char_GoJerryScript_8ba631a7412d8d81(C.char(_swig_i_0))
}


type SwigcptrJerry_instance_t uintptr
type Jerry_instance_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrJerry_instance_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint16_t uintptr
type Uint16_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint16_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint32_t uintptr
type Uint32_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint32_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint8_t uintptr
type Uint8_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint8_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUintptr_t uintptr
type Uintptr_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUintptr_t) Swigcptr() uintptr {
	return uintptr(p)
}

